apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: us.gcr.io/workable-323103/query-services:latest
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-srv
spec:
  selector:
    app: kafka-producer
  ports:
    - name: kafka-producer
      protocol: TCP
      port: 2020
      targetPort: 2020
