apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker0
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "0"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zoo-service:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            # - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
            #   value: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
            # - name: KAFKA_CFG_LISTENERS
            #   value: CLIENT://:9092,EXTERNAL://:9093
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://127.0.0.1:9092
              # value: CLIENT://kafka-service:9092,EXTERNAL://34.87.36.200:32106
            # - name: KAFKA_INTER_BROKER_LISTENER_NAME
            #   value: CLIENT
          volumeMounts:
            - name: kafka-volume
              mountPath: /app/
      volumes:
        - name: kafka-volume
          persistentVolumeClaim:
            claimName: kafka-volume

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: default
